// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKVAOukcsnEthTd_TkHD4JPaZabFp398',
    appId: '1:408012370792:web:a938c24a7f13da56b91cdd',
    messagingSenderId: '408012370792',
    projectId: 'onlinecoach-3f114',
    authDomain: 'onlinecoach-3f114.firebaseapp.com',
    storageBucket: 'onlinecoach-3f114.firebasestorage.app',
    measurementId: 'G-8C4MEKNPE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANEfG_DEorRAGsv4WW0jTbdJJBXDgxNM',
    appId: '1:408012370792:android:8066160fd79f4572b91cdd',
    messagingSenderId: '408012370792',
    projectId: 'onlinecoach-3f114',
    storageBucket: 'onlinecoach-3f114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6teGqhQ_maFKPLEFGdtjrkmSNzYhPo8Q',
    appId: '1:408012370792:ios:7f3981d19e2a4f02b91cdd',
    messagingSenderId: '408012370792',
    projectId: 'onlinecoach-3f114',
    storageBucket: 'onlinecoach-3f114.firebasestorage.app',
    iosBundleId: 'com.example.onlineCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6teGqhQ_maFKPLEFGdtjrkmSNzYhPo8Q',
    appId: '1:408012370792:ios:7f3981d19e2a4f02b91cdd',
    messagingSenderId: '408012370792',
    projectId: 'onlinecoach-3f114',
    storageBucket: 'onlinecoach-3f114.firebasestorage.app',
    iosBundleId: 'com.example.onlineCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTKVAOukcsnEthTd_TkHD4JPaZabFp398',
    appId: '1:408012370792:web:fdf72c64dc257e66b91cdd',
    messagingSenderId: '408012370792',
    projectId: 'onlinecoach-3f114',
    authDomain: 'onlinecoach-3f114.firebaseapp.com',
    storageBucket: 'onlinecoach-3f114.firebasestorage.app',
    measurementId: 'G-67NJ43W5YZ',
  );
}
